In [2]:
from commonfunctions import *
path = '../inputs/'

In [3]:
def integral_image(img):
    rows,cols = img.shape
    int_img = np.zeros(img.shape)
    int_img[0][0] = img[0][0]
    for r in range(1,rows):
        int_img[r][0] = int_img[r-1][0] + img[r][0]    
    for c in range(1,cols):
        int_img[0][c] = int_img[0][c-1] + img[0][c]  
    for r in range(1,rows):
        for c in range(1,cols):
            int_img[r][c] = img[r][c]+int_img[r][c-1] +int_img[r-1][c] - int_img[r-1][c-1] 
    return int_img

In [4]:
def Segment(img,window,t =10):
    rows,cols = img.shape
    output = np.zeros(img.shape, dtype="uint8")
    int_img = integral_image(img)
    s = int(window/2)
    p_img = np.pad(img,s,"constant")
    p_int = np.pad(int_img,s,'edge')
    for r in range(s+1,rows+s):
        for c in range(s+1,cols+s):
            x1 = c-s
            x2 = c+s
            y1 = r-s
            y2 = r+s
            count = (x2-x1)*(y2-y1)
            sum = p_int[y2,x2] - p_int[y2,x1-1] - p_int[y1-1,x2] + p_int[y1-1,x1-1]
            if(img[r-s][c-s]*count)<=(sum*(100-t)/100):
                output[r-s][c-s]=0
            else:
                output[r-s][c-s]=255
    return output        
                

In [5]:
img = [[4,1,2,2],
       [0,4,1,3],
       [3,1,0,4],
       [2,1,3,2],]
print(img)
test = integral_image(np.array(img))

[[4, 1, 2, 2], [0, 4, 1, 3], [3, 1, 0, 4], [2, 1, 3, 2]]


In [6]:
pew = np.pad(test,2,'constant')
print(pew)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  4.  5.  7.  9.  0.  0.]
 [ 0.  0.  4.  9. 12. 17.  0.  0.]
 [ 0.  0.  7. 13. 16. 25.  0.  0.]
 [ 0.  0.  9. 16. 22. 33.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [8]:
sheet = io.imread(path+"music1.jpg")
sheet_t = Segment(rgb2gray(sheet),11,33)
io.imsave('t1.jpg',sheet_t)

In [9]:
sheet2 = io.imread(path+"music2.jpg")
sheet_t2 = Segment(rgb2gray(sheet2),11,33)
io.imsave('t2.jpg',sheet_t2)

In [29]:
print(book.shape)

(240, 320)
